version: "3"

services:
  api:
    tty: true
    container_name: shokubunka_api
    #entrypoint: /go/src/api/startserver.sh
    build:
      context: ./api
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - ./api/app:/go/src/app:consistent
    env_file:
      - development.env

  db:
    container_name: shokubunka_db
    build:
      context: ./db
    # ports:
    #   - 3306:3306
    env_file:
      - development.env
