version: "3"

services:
  # front:
  #   tty: true
  #   container_name: shokubunka_front
  #   build:
  #     context: ./front
  #   entrypoint: /app/startserver.sh
  #   volumes:
  #     - ./front:/app:consistent
  #   depends_on:
  #     - api
  #   ports:
  #     - 8080:8080
  #   env_file: development.env

  api:
    tty: true
    container_name: shokubunka_api
    entrypoint: /go/src/api/startserver.sh
    build:
      context: ./api
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - ./api:/go/src/api:consistent
    env_file:
      - development.env

  db:
    container_name: shokubunka_db
    build:
      context: ./db
    env_file:
      - development.env
