version: "3"

services:
  api:
    tty: true
    container_name: shokubunka_api
    #entrypoint: /go/src/api/startserver.sh
    build:
      context: ./api
    ports:
      - 3000:3000
    volumes:
      - ./api:/go/src:consistent
    env_file:
      - development.env

  db:
    container_name: shokubunka_db
    build:
      context: ./db
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql:consistent
    env_file:
      - development.env
