[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.1"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.3.0"

[[constraint]]
  name = "github.com/qor/qor"
  version = "1.0.0"

[[constraint]]
  name = "github.com/qor/admin"
  version = "1.0.0"
