[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.1"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/qor/admin"

[[override]]
  name = "github.com/qor/roles"
  branch = "master"
